FROM golang:alpine AS builder
RUN apk add --no-cache git
RUN go install go.k6.io/xk6/cmd/xk6@latest
RUN xk6 build v2.0.0-rc1 --with github.com/grafana/xk6-tcp
FROM alpine:latest
COPY --from=builder /go/k6 /usr/bin/k6
ENTRYPOINT ["k6"]
