#!/usr/bin/env bash
# =============================================================================
# phase2_ssh_lockdown.sh — SSH Daemon Hardening for GoBalancer Cluster Node
#
# Target OS  : Ubuntu 22.04 LTS / Debian 12 (Bookworm)
# Run as     : root on the REMOTE server (after provisioning)
# Usage      : sudo bash phase2_ssh_lockdown.sh
#
# What this script does:
#   1. Creates the ~/.ssh directory and authorized_keys file securely
#   2. Backs up the existing sshd_config before modifying it
#   3. Rewrites sshd_config with a fully hardened, production-grade policy
#   4. Validates the new config with sshd -t before applying it
#   5. Installs and configures fail2ban for brute-force protection
#   6. Restarts the SSH daemon and confirms the final state
#
# CRITICAL: Run this ONLY after your public key is in authorized_keys.
#           Otherwise you will permanently lock yourself out of the server.
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[FATAL]${NC} $*" >&2; exit 1; }

# ── 0. Pre-flight ─────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && die "Must be run as root. Try: sudo bash phase2_ssh_lockdown.sh"

AUTHORIZED_KEYS_FILE="/root/.ssh/authorized_keys"
SSHD_CONFIG="/etc/ssh/sshd_config"
BACKUP_SUFFIX=".backup.$(date +%Y%m%d_%H%M%S)"

# ── 1. Verify authorized_keys is populated before touching sshd_config ────────
info "Verifying that at least one public key exists in authorized_keys..."

if [[ ! -f "$AUTHORIZED_KEYS_FILE" ]] || [[ ! -s "$AUTHORIZED_KEYS_FILE" ]]; then
    die "SAFETY BLOCK: $AUTHORIZED_KEYS_FILE is missing or empty.\n\
       \n\
       You MUST add your public key BEFORE running this script.\n\
       From your LOCAL machine, run:\n\
       \n\
         ssh-copy-id -i ~/.ssh/id_ed25519.pub root@<SERVER_IP>\n\
       \n\
       Or manually paste your key into $AUTHORIZED_KEYS_FILE, then re-run."
fi

KEY_COUNT=$(grep -c "ssh-" "$AUTHORIZED_KEYS_FILE" 2>/dev/null || echo 0)
success "Found ${KEY_COUNT} authorised public key(s). Safe to proceed."

# ── 2. Back up the original sshd_config ──────────────────────────────────────
info "Backing up original SSH daemon config..."
cp "$SSHD_CONFIG" "${SSHD_CONFIG}${BACKUP_SUFFIX}"
success "Backup saved to: ${SSHD_CONFIG}${BACKUP_SUFFIX}"

# ── 3. Write the hardened sshd_config ────────────────────────────────────────
info "Writing hardened sshd_config..."

cat > "$SSHD_CONFIG" << 'SSHD_EOF'
# =============================================================================
# /etc/ssh/sshd_config — Hardened SSH Daemon Configuration
# GoBalancer Production Cluster Node
# Generated by phase2_ssh_lockdown.sh
# =============================================================================

# ── Network & Port ────────────────────────────────────────────────────────────

# The port SSH listens on.
# Changing from default (22) adds a minor layer of obscurity against
# opportunistic scanners. UFW must be updated if you change this.
Port 22

# Listen on all available interfaces. For a multi-homed server, you can
# restrict this to the management interface IP only.
ListenAddress 0.0.0.0

# Use IPv4 only. Set to 'any' to re-enable IPv6 if required.
AddressFamily inet

# ── Protocol & Cryptographic Policy ──────────────────────────────────────────

# Only allow the modern SSH Protocol version 2.
# Protocol 1 is cryptographically broken and must never be used.
Protocol 2

# Host keys accepted by the daemon (in order of preference).
# Ed25519 is the strongest; RSA-4096 is included for compatibility.
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# Key Exchange Algorithms: only allow state-of-the-art algorithms.
# Removes older DH groups that are vulnerable to Logjam-style attacks.
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

# Message Authentication Codes: only use Encrypt-then-MAC (ETM) modes
# and modern AEAD ciphers. Prevents padding oracle and CBC-mode attacks.
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

# Symmetric Ciphers: modern, authenticated encryption only.
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# ── AUTHENTICATION — CRITICAL SECURITY SECTION ───────────────────────────────

# ❌ DISABLE password-based authentication entirely.
# This is the most important setting. Once your public key is installed,
# this makes brute-force password attacks completely impossible.
PasswordAuthentication no

# ❌ Disable challenge-response (keyboard-interactive) authentication.
# This is a secondary password mechanism that must also be disabled.
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no

# ❌ Disable PAM password stack for SSH.
# Even with the above disabled, PAM can sometimes allow password auth.
# Set to 'no' for maximum enforcement.
UsePAM no

# ✅ Enable public key authentication (the ONLY allowed method).
PubkeyAuthentication yes

# Location of the authorized public keys file.
AuthorizedKeysFile .ssh/authorized_keys

# ❌ Disable root login with a password.
# Set to 'prohibit-password' (not 'no') to allow emergency key-based root
# access. Set to 'no' to block all root logins entirely (more secure,
# but requires a separate sudo user to be pre-configured first).
PermitRootLogin prohibit-password

# ❌ Disable empty password logins unconditionally.
PermitEmptyPasswords no

# ❌ Disable host-based authentication (legacy, insecure).
HostbasedAuthentication no

# ❌ Disable .rhosts and shosts-style authentication.
IgnoreRhosts yes
IgnoreUserKnownHosts yes

# Number of authentication attempts allowed per connection before disconnect.
# Lower = more resistant to multi-factor brute force.
MaxAuthTries 3

# Maximum simultaneous pending unauthenticated connections.
# Format: start:rate:full
# Starts throttling at 10 pending connections; at 30 pending, 100% are dropped.
MaxStartups 10:30:60

# Maximum number of open sessions per network connection.
MaxSessions 10

# ── Session & Forwarding Policy ───────────────────────────────────────────────

# Time (in seconds) allowed to authenticate before the connection is dropped.
# Tight window prevents slow brute-force probing attacks.
LoginGraceTime 30

# ❌ Disable TCP forwarding.
# Prevents the server from being used as an SSH tunnel/SOCKS proxy by
# potentially compromised or untrusted users.
AllowTcpForwarding no

# ❌ Disable X11 forwarding (no GUI required on a server node).
X11Forwarding no

# ❌ Disable agent forwarding to prevent credential forwarding abuse.
AllowAgentForwarding no

# ❌ Disable SSH tunneled privileged ports.
GatewayPorts no

# ── Logging & Monitoring ──────────────────────────────────────────────────────

# Log facility and verbosity level.
# VERBOSE logs key fingerprints, which is essential for security auditing.
SyslogFacility AUTH
LogLevel VERBOSE

# ── Session Keep-Alive ────────────────────────────────────────────────────────

# Send keep-alive packets to detect dead connections.
# Prevents ghost sessions from consuming resources.
ClientAliveInterval 300
ClientAliveCountMax 2

# Resolve client hostnames for logging. Disabling speeds up connections
# by avoiding reverse-DNS lookups.
UseDNS no

# ── Subsystems ────────────────────────────────────────────────────────────────

# SFTP subsystem (standard; needed for scp and secure file transfers).
Subsystem sftp /usr/lib/openssh/sftp-server

# ── Banner ────────────────────────────────────────────────────────────────────

# Display a legal warning before authentication.
# This is required for many compliance frameworks (SOC2, HIPAA, PCI-DSS).
Banner /etc/ssh/sshd_banner

SSHD_EOF

success "Hardened sshd_config written."

# ── 4. Write the Legal Banner ─────────────────────────────────────────────────
info "Creating SSH login banner..."
cat > /etc/ssh/sshd_banner << 'BANNER_EOF'
╔══════════════════════════════════════════════════════════════╗
║          GoBalancer — Production Infrastructure Node          ║
║                                                              ║
║  AUTHORISED ACCESS ONLY.                                     ║
║  All connections are monitored and logged.                   ║
║  Unauthorised access is strictly prohibited and will be      ║
║  reported to the appropriate authorities.                    ╚═══════════════════════════════════════════════════════════════╝

BANNER_EOF
success "Login banner created at /etc/ssh/sshd_banner."

# ── 5. Regenerate Modern Host Keys (if not already Ed25519) ──────────────────
info "Ensuring Ed25519 host key exists (strongest available)..."

if [[ ! -f /etc/ssh/ssh_host_ed25519_key ]]; then
    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -q
    success "New Ed25519 host key generated."
else
    success "Ed25519 host key already present."
fi

# ── 6. Validate the new config before applying it ─────────────────────────────
info "Validating sshd_config syntax with 'sshd -t'..."
if ! sshd -t -f "$SSHD_CONFIG"; then
    die "sshd_config validation FAILED. Restoring backup and aborting.\n\
         Backup is at: ${SSHD_CONFIG}${BACKUP_SUFFIX}"
    cp "${SSHD_CONFIG}${BACKUP_SUFFIX}" "$SSHD_CONFIG"
fi
success "Config validation passed."

# ── 7. Install & Configure fail2ban ──────────────────────────────────────────
info "Installing fail2ban for brute-force protection..."
apt-get install -y -q fail2ban

# Write a local jail configuration (overrides defaults without editing originals)
cat > /etc/fail2ban/jail.local << 'JAIL_EOF'
[DEFAULT]
# Ban IPs that fail authentication for 1 hour
bantime  = 3600
findtime = 600
maxretry = 3
backend  = systemd

[sshd]
enabled  = true
port     = ssh
logpath  = %(sshd_log)s
maxretry = 3
bantime  = 86400
JAIL_EOF

systemctl enable fail2ban
systemctl restart fail2ban
success "fail2ban installed and configured (3 failures → 24-hour IP ban)."

# ── 8. Reload the SSH Daemon ─────────────────────────────────────────────────
info "Reloading SSH daemon to apply new configuration..."

# Use 'reload' not 'restart' to avoid dropping the current session
systemctl reload sshd || systemctl restart sshd
success "SSH daemon reloaded successfully."

# ── 9. Final Report ───────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅  Phase 2: SSH Lockdown Complete!${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${CYAN}Password Auth     :${NC} $(sshd -T 2>/dev/null | grep -i passwordauthentication | head -1)"
echo -e "  ${CYAN}PubKey Auth       :${NC} $(sshd -T 2>/dev/null | grep -i pubkeyauthentication | head -1)"
echo -e "  ${CYAN}PermitRootLogin   :${NC} $(sshd -T 2>/dev/null | grep -i permitrootlogin | head -1)"
echo -e "  ${CYAN}Max Auth Tries    :${NC} $(sshd -T 2>/dev/null | grep -i maxauthtries | head -1)"
echo -e "  ${CYAN}fail2ban Status   :${NC} $(systemctl is-active fail2ban)"
echo ""
echo -e "  ${YELLOW}⚠️  IMPORTANT: Open a NEW terminal tab and verify you can still${NC}"
echo -e "  ${YELLOW}   SSH in with your key BEFORE closing this session.${NC}"
echo -e "  ${YELLOW}   Command: ssh -i ~/.ssh/id_ed25519 root@<SERVER_IP>${NC}"
echo ""
echo -e "  ${YELLOW}Next Step: Phase 3 — Layer-4 TLS Splicing in Go${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════════════${NC}"
